apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: readit-secrets

spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "70aef1be-d837-4d2e-9934-f7cbdbc0f91e"
    keyvaultName: "readit123-kv"
    tenantId: "0b274f90-6e71-40a3-b56c-a24cc45bd20c"

    objects: |
      array:
        - |
          objectName: servicebus-connection
          objectType: secret
        - |
          objectName: servicebus-queue
          objectType: secret
