apiVersion: apps/v1
kind: Deployment

metadata:
  name: order-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: order

  template:
    metadata:
      labels:
        app: order

    spec:
      containers:
        - name: order
          image: readitacr123.azurecr.io/order-service:v13

          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets"
              readOnly: true

      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true

            volumeAttributes:
              secretProviderClass: "readit-secrets"
