apiVersion: apps/v1
kind: Deployment

metadata:
  name: order-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: order

  template:
    metadata:
      labels:
        app: order

    spec:
      containers:
        - name: order
          image: readitacr123.azurecr.io/order-service:v3-observability

          ports:
            - containerPort: 80

          env:
            - name: APPLICATIONINSIGHTS_CONNECTION_STRING
              value: "InstrumentationKey=...;IngestionEndpoint=https://..."

            - name: SERVICEBUS_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: servicebus-secret
                  key: SERVICEBUS_CONNECTION

            - name: SERVICEBUS_QUEUE
              value: "order-queue"

          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets"
              readOnly: true

      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true

            volumeAttributes:
              secretProviderClass: "readit-secrets"
