name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

env:
  ACR_NAME: readitacr123
  RESOURCE_GROUP: rg-readit
  AKS_CLUSTER: readit-aks

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Catalog
        run: |
          docker build -t $ACR_NAME.azurecr.io/catalog-service:${{ github.sha }} ./catalog-service
          az acr login --name $ACR_NAME
          docker push $ACR_NAME.azurecr.io/catalog-service:${{ github.sha }}

      - name: Build and Push Cart
        run: |
          docker build -t $ACR_NAME.azurecr.io/cart-service:${{ github.sha }} ./cart-service
          docker push $ACR_NAME.azurecr.io/cart-service:${{ github.sha }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --name $AKS_CLUSTER --resource-group $RESOURCE_GROUP --overwrite-existing

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/catalog-deployment catalog=$ACR_NAME.azurecr.io/catalog-service:${{ github.sha }}
          kubectl set image deployment/cart-deployment cart=$ACR_NAME.azurecr.io/cart-service:${{ github.sha }}
